name: build_master


on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build-master:
    runs-on: ubuntu-latest
    container:
      image: texlive/texlive:latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download build script
        run: |
          curl -O https://raw.githubusercontent.com/seggiani-luca/note-tools/refs/heads/main/make_master_monolithic.py

      - name: Run LaTeX build script
        run: |
          python make_master_monolithic.py
          
      - name: Commit and push PDF
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git checkout -B build
          git add master/master.pdf
          git commit -m "Updated master" || echo "No changes to commit"
          git push -f origin build
