name: build_master


on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build-master:
    runs-on: ubuntu-latest
    container:
      image: texlive/texlive:latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download build script
        run: |
          curl -O https://raw.githubusercontent.com/seggiani-luca/note-tools/refs/heads/main/make_master_monolithic.py

      - name: Run LaTeX build script
        run: |
          python make_master_monolithic.py
          rm ./master/master.aux ./master/master.log ./master/master.out
          
      - name: Deploy PDF to build branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: build
          publish_dir: ./master 
